version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - VITE_OUTPUT="./dist" npm run build
cache:
  paths:
    - "node_modules/**/*"
artifacts:
  files:
    - "dist/**/*"
