version: 0.2

env:
  variables:
    VITE_OUTPUT: "./dist"
    NODE_ENV: "production"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
cache:
  paths:
    - "node_modules/**/*"
artifacts:
  files:
    - "**/*"
  base-directory: dist
